version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/QuickCommerce
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: sqlite:latest
    volumes:
      - sqlite_data:/var/lib/sqlite3